### PR TITLE
[parse_texte] parse new AN texts #120

### PR DESCRIPTION
**Pull request by mdamien**
Makes `parse_text` able to parse the .raw urls like http://www.assemblee-nationale.fr/dyn/docs/PRJLANR5L15B2623.raw

Not yet able to parse URLs like this: http://www.assemblee-nationale.fr/dyn/15/textes/l15b2623_projet-loi

### CODE REVIEW

**Comment by paulineleon** [comment]
FYI [this script](https://git.en-root.org/tricoteuses/tricoteuses-assemblee/-/blob/master/src/scripts/retrieve_documents.ts) is run by cron daily to feed [this repository](https://git.en-root.org/tricoteuses/data/assemblee-textes) with PDF & HTML files retrieved from http://assemblee-nationale, using the new URL scheme and fallback to the old ones when that fails.

Some documents cannot be retrieved (PDF and/or HTML) and a [report on their status](https://git.en-root.org/tricoteuses/tricoteuses-assemblee-qa/-/blob/master/checks/textes-00009.md) is updated daily.

**Comment by mdamien** [comment]
Hum, maybe I could just use your repository as a proxy to get the HTML of a doc, would it be ok ?

**Comment by mdamien** [comment]
Oops, this PR is not yet ready, the tests are failing

**Comment by paulineleon** [comment]
> Hum, maybe I could just use your repository as a proxy to get the HTML of a doc, would it be ok ?

Yes, that's the goal of this repository: a stable (namespace & content) source for documents harvested from the ever moving assemblee-nationale.fr web site. And the git history keeps all variations of HTML content over time so that ancient scripts are not forced to adapt (except for new documents, of course).

**Comment by mdamien** [comment]
Cool !

**Comment by Fallen70** [comment]
You should also have a look to PLF texts :
http://www.assemblee-nationale.fr/dyn/15/textes/l15b2272_projet-loi
These raw file http://www.assemblee-nationale.fr//dyn/docs/PRJLANR5L15B2272.raw are not using the same html  rendering.

**Comment by mdamien** [comment]
Nice, nice, now I wonder if I should parse those pages instead: http://www.senat.fr/tableau-historique/pjlf2020.html

**Comment by paulineleon** [comment]
> You should also have a look to PLF texts :
http://www.assemblee-nationale.fr/dyn/15/textes/l15b2272_projet-loi
These raw file http://www.assemblee-nationale.fr/dyn/docs/PRJLANR5L15B2272.raw are not using the same html rendering.

http://www.assemblee-nationale.fr/dyn/15/textes/l15b2272_projet-loi actually includes http://www.assemblee-nationale.fr/dyn/docs/PRJLANR5L15B2272.raw in an iframe

**Comment by mdamien** [comment]
> http://www.assemblee-nationale.fr/dyn/15/textes/l15b2272_projet-loi actually includes http://www.assemblee-nationale.fr/dyn/docs/PRJLANR5L15B2272.raw in an iframe

I think he meant the rendering is not the same (the articles title especially)

**Comment by Fallen70** [comment]
> I think he meant the rendering is not the same (the articles title especially)

This is what I meant, sorry if it was a bit fuzzy.

**Comment by mdamien** [comment]
Made a quick script to extract one text from "la loi en fabrication":

```
from bs4 import BeautifulSoup as Soup

html = open('tableau.html').read()

html = html.replace('text-decoration: line-through;', '')
html = html.replace('border-bottom: 3px double;', '')
html = html.replace('▫', '')

soupe = Soup(html, 'lxml')

TEXT_TO_EXTRACT = 0

for article in soupe.select('table'):
	for ligne in article.select('.texte-ligne'):
		cellule = ligne.select('.tableauComparatifCell .dispositif')[TEXT_TO_EXTRACT]
		
		if not cellule.text.strip():
			continue

		classes = cellule.attrs['class']

		if 'TCTexte' in classes:
			print(cellule)
		else:
			print('<b>', cellule, '</b>')
```

The converted text can be fed into `tlfp-parse-text` and, magic, it works !

**Comment by mdamien** [comment]
Update on things left to do from this PR:

- [ ] section titles missing space
image
- [ ] `nodesputes_id` not yet the same (used for amendments)
image
- [ ] **definitive lecture depot text is not the right one** see https://github.com/regardscitoyens/Issues-Parlement/issues/61

diff with the current regression test cases: https://github.com/regardscitoyens/the-law-factory-parser-test-cases/commit/d1de6b08dc5a8faf69e41d62bc7242614af64c1b

**Comment by mdamien** [comment]
There's a difficult decision to make, I think I should merge this PR even if it's not 100% regression-free but at least LFDLL is gonna be running again. The main thing missing is related to how bad the open data is and it should be fixed by the AN I think.

**Pull request merged**
