### PR TITLE
Turn the repository into a Python package

### LINKED ISSUE #62: parse_texte.py as a Python module
Hi,

I refactored [parse_texte.py](https://github.com/regardscitoyens/the-law-factory-parser/blob/master/scripts/collectdata/parse_texte.py) so it can be used as a Python module:

https://github.com/Legilibre/duralex/blob/master/duralex/bill_parser.py

I've also added a [fix](https://github.com/Legilibre/duralex/blob/master/duralex/bill_parser.py#L363).

I'd like to make sure we don't maintain two separate versions.
So I'd like to make a PR for this new version to be merged here.
Then I would make DuraLex depend on a the-law-factory-parser pip package.

So two questions:

* would you be interested in such a pull request?
* is there a the-law-factory-parser pip package? otherwise, how should I handle the dependency between our two projects ? I'm guessing I should git clone it at the root of the DuraLex projet and update it manually... or use a git submodule ?

Thanks!

### PR DESCRIPTION
**Pull request by davidbgk**
There is a lot left to discussion, I only made `parse-texte` available for now given that it is my need and I am not sure which other parts are useful as scripts.

The `install_requires` requirements are hard coded for now and match those related to the `parse_texte` script but that can be improved, not sure if we want to let the option to install only parts of the package and so on.

Fix #62

CI will hopefully/probably complain :-)

### CODE REVIEW

**Comment by mdamien** [comment]
A bit of context: The duality was introduced because the script can be called by themselves or by other part of the code. The hack was latter even transformed to [hacking into the PYTHONPATH](https://github.com/regardscitoyens/the-law-factory-parser/blob/master/tools/compute_stats.py#L2).

Your solution very much clean all this mess and is very welcome !

**Comment by boogheta** [comment]
Really cool!
A few remarks focused on the setup.py:
- I realise you've set MIT for the License, although this repo used to be under AGPL originally (which doesn't make much sense and should rather be GPL), the LICENCE file was apparently forgotten during the huge refacto, I'll readd one right away.
- Also I guess the classifiers could precise different python versions accepted (I believe python 3.4 breaks, so only 3.5 and 3.6, and also pypy 3.5)
- And as you pointed out, we need to deploy updated packages for our 3 dependencies and then include those in the setup's dependencies instead

**Comment by davidbgk** [comment]
I tried to address every concerns, things left to do:

1. move more commands to the `scripts` section of the `setup.py` (I don't have enough knowledge on the repo to take that task without guidance)
2. release and integrate `legipy` dependency (good job on `senapi` and `anpy` so far 👍)
3. publish this package on pypi and celebrate 🎊

So far, if only the point 3 is done it will be enough for my use case but I'm open to more collaboration.

**Comment by ronnix** [comment]
@davidbgk the `setup.py` uses `packages=['tlfp']` which correctly installs the `tlfp` package, but not the `tlfp.tools` subpackage. I would recommend using `packages=find_packages()` to make sure everything gets picked up, and no updates to the package list are needed if the source tree organization ever changes.

**Comment by mdamien** [comment]
I'm gonna try to merge that first, it's already a nice PR, now we will even be able to publish the parser on pypi

**Comment by ronnix** [comment]
I created another PR with the packaging fix mentioned in my previous comment: #78

**Pull request merged**
